logger_error: Add missing "os" import in testcase script
The testcase was working without before, but that was only by
chance, because we're doing a wildcard import of the support
module. Since that module will disappear when we transition
the testsuite to pytest, best to import os explicitly now.

TN: U530-006
Change-Id: I3288e3940d1370fcb0c2c6b0dcd71e05cacc2eb5